# Assignment 1
## Useful 5 Pytorch Functions

An short introduction about PyTorch and about the chosen functions. 
- **prod()**
- **squeeze()**
- **randint_like()**
- **sqrt()**
- **sum()**

In [4]:
# Import torch and other required modules
!pip3 install torchvision
import torch


     |████████████████████████████████| 6.6 MB 1.3 MB/s eta 0:00:01     |████████████▏                   | 2.5 MB 1.3 MB/s eta 0:00:04
     |████████████████████████████████| 2.1 MB 33.5 MB/s eta 0:00:01
     |████████████████████████████████| 20.1 MB 28.6 MB/s eta 0:00:01
     |████████████████████████████████| 752.0 MB 10 kB/s s eta 0:00:01    |▋                               | 14.0 MB 28.6 MB/s eta 0:00:26     |█▎                              | 29.7 MB 28.6 MB/s eta 0:00:26     |█▎                              | 30.4 MB 28.6 MB/s eta 0:00:26     |█████▎                          | 125.2 MB 47.2 MB/s eta 0:00:14     |█████████▋                      | 225.2 MB 2.7 MB/s eta 0:03:12     |████████████▌                   | 294.2 MB 40.5 MB/s eta 0:00:12     |██████████████▍                 | 339.3 MB 195 kB/s eta 0:35:07     |███████████████▎                | 358.7 MB 39.9 MB/s eta 0:00:10     |████████████████▏               | 379.1 MB 39.9 MB/s eta 0:00:10     |██████████████████▍       

## Function 1 - `torch.prod()`

Returns the product of all elements in the `input` tensor.

In [8]:
t1 = torch.randn(1,3)
t11=torch.prod(t1)
t11

tensor(-1.4605)

In [47]:
t2 = torch.randn(3, 4, (5))#Matrix is bigger
t22=torch.prod(t2,1)#Dimension is 1
t22

tensor([[ 0.0045, -0.0433, -0.0759,  0.1615,  0.2027],
        [-0.0835,  0.8342, -0.0033,  0.2841,  0.1436],
        [ 0.0044,  0.0138, -0.0918,  0.0142,  0.0590]])

In [50]:
t2 = torch.randn(3, 4, (5))#Matrix is bigger
t22=torch.prod(t2,5)#Dimension is out of the randn value given
t22

IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 5)

## Function 2 - `torch.squeeze()`

For example, if input is of shape: `(A×1×B×C×1×D)` then the out tensor will be of shape :- `(A×B×C×D)`.

In [60]:
a=torch.randint(10, (2, 2))
b=torch.squeeze(a,1)
b

tensor([[8, 4],
        [4, 4]])

In [92]:
x = torch.zeros(5,4,5,2,1,2)
y=torch.squeeze(x)#Add ,0 to unsqueeze it 
y.size()

torch.Size([5, 4, 5, 2, 2])

In [100]:
x = torch.zeros(5,4,5,2,1,2)
z=torch.zeros(5,2,1,1,3,5)
y=torch.squeeze(x,z,0) 
y.size()

TypeError: squeeze() received an invalid combination of arguments - got (Tensor, Tensor, int), but expected one of:
 * (Tensor input)
 * (Tensor input, name dim)
 * (Tensor input, int dim)


## Function 3 - torch.randint_like()

Returns a tensor filled with **random integers** generated uniformly between `low value` and `high value`.

In [121]:
a=torch.tensor(100)
c=torch.randint_like(a,high=55)
c

tensor(50)

In [133]:
a=torch.tensor(100)
c=torch.randint_like(a,low=50,high=55,dtype=float)#Change the low value
c

tensor(53., dtype=torch.float64)

In [143]:
a=torch.tensor(100,10)#2 values entered
c=torch.randint_like(a,low=50,high=55,dtype=float)
c

TypeError: tensor() takes 1 positional argument but 2 were given

## Function 4 - `torch.sqrt()`

*Returns a new tensor with the square-root of the `elements of tensor`.*

In [160]:
a = torch.randn(5)
torch.sqrt(a)

tensor([0.6883,    nan, 0.0643,    nan, 0.8555])

In [177]:
a=torch.tensor(100)
b=torch.randint_like(a,low=40,high=55,dtype=float)
c=torch.sqrt(b),b
c

(tensor(7.1414, dtype=torch.float64), tensor(51., dtype=torch.float64))

In [178]:
a=torch.tensor(100)
b=torch.randint_like(a,low=41,high=55)#dtype must be float
c=torch.sqrt(b)
c

RuntimeError: sqrt_vml_cpu not implemented for 'Long'

## Function 5 - `torch.sum()`

**Returns the sum of all elements in the `tensor`.**

In [201]:
a=torch.randn(2,11,dtype=float)
b = torch.sum(a)
b

tensor(-1.3641, dtype=torch.float64)

In [215]:
b=torch.randint(10, (5, 5))#return 5x5 matrix
c=torch.sum(b,1)#return total of matrix
c

tensor([24, 24, 11, 31, 30])

In [223]:
b=torch.randint(10, (5, 5))#return 5x5 matrix
c=torch.sum(b,2)#return total of matrix,but error is of dimension
c

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

## Conclusion

This where the Basic concepts understood in these assignment.

## Reference Links
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* https://pytorch.org/docs/stable/torch.html#torch.randint

In [224]:
!pip install jovian --upgrade --quiet

In [227]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
